"""F8-P2 discrete-time DSP layer (NEW): public surface."""

from academic_core.domain.engineering.dsp.dft import (
    MAX_DIRECT_DFT_N,
    MAX_FFT_N,
    circular_convolve,
    dft as dft_direct,
    dtft_at,
    fft,
    frequency_bins,
    idft,
    ifft,
    nyquist_index,
    twiddle,
)
from academic_core.domain.engineering.dsp.filters import (
    MAX_SOS_SECTIONS,
    BilinearResult,
    LinearPhaseReport,
    SOSReport,
    StabilityReport,
    bilinear_back,
    bilinear_design,
    cascade_evaluate,
    fir_group_delay_at,
    iir_stability,
    linear_phase_report,
    sos_decompose,
)
from academic_core.domain.engineering.dsp.margins_d import (
    DigitalMarginsReport,
    digital_margins,
    gain_crossovers_d,
    phase_crossovers_d,
)
from academic_core.domain.engineering.dsp.report import (
    SCHEMA,
    DspDocument,
    compare,
    dumps,
    loads,
    replay,
)
from academic_core.domain.engineering.dsp.sampling import (
    alias_of,
    nyquist_frequency,
    nyquist_rate,
    nyquist_verdict,
    reconstruct,
    sample_times,
    to_sequence_uniform,
)
from academic_core.domain.engineering.dsp.sequences import (
    MAX_SEQUENCE_N,
    Sequence,
    sample_signal,
    to_sample_value,
)
from academic_core.domain.engineering.dsp.ztrans import (
    MAX_Z_ORDER,
    TransferFunctionZ,
    complementary_z,
    delay_coeffs,
    feedback_z,
    make_hz,
    sensitivity_z,
    series_z,
    z_pair,
)

ENGINE_VERSION = "f8p2-dsp/1"

__all__ = [
    "ENGINE_VERSION",
    "MAX_SEQUENCE_N",
    "MAX_FFT_N",
    "MAX_DIRECT_DFT_N",
    "MAX_Z_ORDER",
    "MAX_SOS_SECTIONS",
    "Sequence",
    "to_sample_value",
    "sample_signal",
    "dft_direct",
    "idft",
    "fft",
    "ifft",
    "twiddle",
    "dtft_at",
    "circular_convolve",
    "frequency_bins",
    "nyquist_index",
    "TransferFunctionZ",
    "make_hz",
    "series_z",
    "feedback_z",
    "sensitivity_z",
    "complementary_z",
    "delay_coeffs",
    "z_pair",
    "BilinearResult",
    "bilinear_design",
    "bilinear_back",
    "StabilityReport",
    "iir_stability",
    "SOSReport",
    "sos_decompose",
    "cascade_evaluate",
    "LinearPhaseReport",
    "linear_phase_report",
    "fir_group_delay_at",
    "DigitalMarginsReport",
    "digital_margins",
    "gain_crossovers_d",
    "phase_crossovers_d",
    "nyquist_verdict",
    "nyquist_rate",
    "nyquist_frequency",
    "alias_of",
    "reconstruct",
    "sample_times",
    "to_sequence_uniform",
    "SCHEMA",
    "DspDocument",
    "dumps",
    "loads",
    "compare",
    "replay",
]
