"""F8-D2 complex linear solver: exact, high-precision, rank, adversarial.

Conventions: EXACT assertions are representation-exact (no tolerances).
HIGH_PRECISION assertions carry explicit tolerances stated at the site.
Expected values for the principal cases are derived independently
(hand computation, Cramer/determinant formulas coded separately from the
solver, forward products) — never generated by the solver under test.
"""
import ast
import json
import pathlib
import time
from decimal import Decimal
from fractions import Fraction

import pytest

from academic_core.domain.engineering.math import DecimalComplex, RationalComplex
from academic_core.domain.engineering.math.linsolve import (
    ComplexLinearError,
    ComplexLinearProblem,
    DimensionMismatchError,
    EmptySystemError,
    InvalidEntryError,
    InvalidModeError,
    NonSquareError,
    NumericMode,
    SolveStatus,
    conjugate_system,
    matvec,
    solve,
)

TOL = Decimal("1E-40")  # default absolute tolerance for HP comparisons


def R(re, im=0):
    return RationalComplex(Fraction(re), Fraction(im))


def C(re, im=0):
    return DecimalComplex(Decimal(str(re)), Decimal(str(im)))


def close(a: DecimalComplex, b: DecimalComplex, tol=TOL) -> bool:
    from academic_core.domain.engineering.math.trig import make_context

    ctx = make_context()
    d = a - b
    return ctx.sqrt(d.squared_modulus()) <= tol


def close_list(xs, ys, tol=TOL) -> bool:
    return len(xs) == len(ys) and all(close(x, y, tol) for x, y in zip(xs, ys))


def cramer2(A, b):
    """Independent 2x2 reference via Cramer's rule (no elimination)."""
    a, bb = A[0][0], A[0][1]
    c, d = A[1][0], A[1][1]
    e, f = b[0], b[1]
    det = a * d - bb * c
    assert not det.is_zero_exact()
    return ((e * d - bb * f) / det, (a * f - e * c) / det)


def det3(M):
    """Independent 3x3 determinant via the Rule of Sarrus (no elimination)."""
    a, b, c = M[0]
    d, e, f = M[1]
    g, h, i = M[2]
    return a * e * i + b * f * g + c * d * h - c * e * g - b * d * i - a * f * h


def cramer3(A, b):
    """Independent 3x3 reference via Cramer's rule (no elimination)."""
    det = det3(A)
    assert not det.is_zero_exact()
    cols = list(zip(*A))
    out = []
    for k in range(3):
        Mk = [list(r) for r in zip(*cols)]
        for r in range(3):
            Mk[r][k] = b[r]
        out.append(det3(Mk) / det)
    return tuple(out)


# -- A. EXACT basics ---------------------------------------------------------------

def test_exact_1x1_hand_derived():
    # (2+j) x = 4+2j  =>  x = 2 by hand: (2+j)*2 = 4+2j.
    p = ComplexLinearProblem.from_sequences(
        [[R(2, 1)]], [R(4, 2)])
    r = solve(p, NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == (R(2, 0),)
    assert (r.rank_A, r.rank_augmented) == (1, 1)


def test_exact_2x2_spec_example():
    # (1+j)x + (2-j)y = 3 ; (2-j)x + (4+j)y = 7 ; det = 9j.
    # Hand-derived: x = 10/9+2/9j, y = 10/9-1/9j.
    A = [[R(1, 1), R(2, -1)], [R(2, -1), R(4, 1)]]
    b = [R(3), R(7)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == (
        RationalComplex(Fraction(10, 9), Fraction(2, 9)),
        RationalComplex(Fraction(10, 9), Fraction(-1, 9)),
    )
    assert r.solution == cramer2(A, b)  # independent formula agrees


def test_exact_2x2_cramer_crosscheck_seeded():
    import random

    rng = random.Random(7)
    for _ in range(10):
        vals = [R(rng.randint(-5, 5), rng.randint(-5, 5)) for _ in range(6)]
        A = [[vals[0], vals[1]], [vals[2], vals[3]]]
        b = [vals[4], vals[5]]
        det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
        if det.is_zero_exact():
            continue
        r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
        assert r.status == SolveStatus.SOLVED
        assert r.solution == cramer2(A, b)


def test_exact_3x3_cofactor_crosscheck():
    A = [[R(2), R(1, 1), R(0)], [R(1, -1), R(3), R(1, 2)], [R(0), R(1, -2), R(2, 2)]]
    b = [R(1, 1), R(2), R(3, -1)]
    assert not det3(A).is_zero_exact()
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == cramer3(A, b)


def test_exact_identity():
    n = 4
    A = [[R(1) if i == j else R(0) for j in range(n)] for i in range(n)]
    b = [R(i + 1, -(i + 1)) for i in range(n)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == tuple(b)


def test_exact_triangular():
    A = [[R(2), R(0), R(0)], [R(1, 1), R(3, -1), R(0)], [R(1), R(2), R(1, 1)]]
    x_true = [R(1, 1), R(2, -1), R(3)]
    b = list(matvec(A, x_true))
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == tuple(x_true)


def test_exact_purely_real_matrix():
    A = [[R(2), R(1)], [R(1), R(3)]]
    b = [R(5), R(6)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == cramer2(A, b)


def test_exact_purely_imaginary_matrix():
    J = R(0, 1)
    A = [[2 * J, J], [J, 3 * J]]
    b = [R(1, 1), R(2, -1)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == cramer2(A, b)


def test_exact_initial_zero_pivot():
    # First pivot is zero; deterministic row scan must still solve.
    A = [[R(0), R(1)], [R(1), R(1, 1)]]
    b = [R(2, 1), R(3)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == cramer2(A, b)


def test_exact_reconstruction_identity():
    import random

    rng = random.Random(21)
    for _ in range(8):
        n = 3
        A = [[R(rng.randint(-4, 4), rng.randint(-4, 4)) for _ in range(n)]
             for _ in range(n)]
        b = [R(rng.randint(-4, 4), rng.randint(-4, 4)) for _ in range(n)]
        r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
        if r.status != SolveStatus.SOLVED:
            continue
        assert tuple(matvec(A, r.solution)) == tuple(b)  # A*x == b exactly


# -- B. augmented trio ---------------------------------------------------------------

def test_augmented_identity_solved():
    r = solve(ComplexLinearProblem.from_sequences(
        [[R(1), R(0)], [R(0), R(1)]], [R(1), R(2)]))
    assert r.status == SolveStatus.SOLVED
    assert (r.rank_A, r.rank_augmented) == (2, 2)
    assert r.solution == (R(1), R(2))


def test_augmented_dependent_consistent_singular():
    r = solve(ComplexLinearProblem.from_sequences(
        [[R(1), R(2)], [R(2), R(4)]], [R(3), R(6)]))
    assert r.status == SolveStatus.SINGULAR
    assert (r.rank_A, r.rank_augmented) == (1, 1)
    assert r.solution is None


def test_augmented_dependent_contradictory_inconsistent():
    r = solve(ComplexLinearProblem.from_sequences(
        [[R(1), R(2)], [R(2), R(4)]], [R(3), R(7)]))
    assert r.status == SolveStatus.INCONSISTENT
    assert (r.rank_A, r.rank_augmented) == (1, 2)
    assert r.solution is None


# -- C. complex singular / inconsistent -----------------------------------------------

def test_complex_singular_dependent_rows():
    A = [[R(1, 1), R(2, -1)], [R(2, 2), R(4, -2)]]
    b = [R(1), R(2)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SINGULAR
    assert (r.rank_A, r.rank_augmented) == (1, 1)


def test_complex_inconsistent_dependent_rows():
    A = [[R(1, 1), R(2, -1)], [R(2, 2), R(4, -2)]]
    b = [R(1), R(3)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.INCONSISTENT
    assert (r.rank_A, r.rank_augmented) == (1, 2)


def test_zero_matrix_singular_vs_inconsistent():
    A = [[R(0), R(0)], [R(0), R(0)]]
    r0 = solve(ComplexLinearProblem.from_sequences(A, [R(0), R(0)]))
    assert r0.status == SolveStatus.SINGULAR
    assert (r0.rank_A, r0.rank_augmented) == (0, 0)
    r1 = solve(ComplexLinearProblem.from_sequences(A, [R(1), R(0)]))
    assert r1.status == SolveStatus.INCONSISTENT
    assert (r1.rank_A, r1.rank_augmented) == (0, 1)


# -- D. HIGH_PRECISION basics --------------------------------------------------------------

def test_hp_1x1():
    r = solve(ComplexLinearProblem.from_sequences(
        [[C(2, 1)]], [C(4, 2)]), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert close(r.solution[0], C(2, 0))
    assert r.working_precision == 50


def test_hp_2x2_matches_exact_within_tolerance():
    A = [[R(1, 1), R(2, -1)], [R(2, -1), R(4, 1)]]
    b = [R(3), R(7)]
    exact = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    hp = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert hp.status == SolveStatus.SOLVED
    assert hp.solution is not None
    exp = [DecimalComplex.from_rational(e) for e in exact.solution]
    assert close_list(list(hp.solution), exp)
    assert hp.backward_error is not None and hp.backward_error <= Decimal("1E-30")


def test_hp_3x3_dense_matches_exact():
    A = [[R(3), R(1, 1), R(2)], [R(1, -2), R(4), R(0, 1)],
         [R(1), R(1, 1), R(5, -1)]]
    b = [R(1), R(2, 1), R(-1, 2)]
    exact = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert exact.status == SolveStatus.SOLVED
    hp = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert hp.status == SolveStatus.SOLVED
    exp = [DecimalComplex.from_rational(e) for e in exact.solution]
    assert close_list(list(hp.solution), exp)


def test_hp_identity_and_diagonal():
    n = 5
    A = [[C(2, 1) if i == j else C(0) for j in range(n)] for i in range(n)]
    b = [C(i - 2, i + 1) for i in range(n)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert close_list(list(r.solution), [x / C(2, 1) for x in b], Decimal("1E-45"))


def test_hp_purely_real_and_imaginary():
    Ar = [[C(2), C(1)], [C(1), C(3)]]
    br = [C(5), C(6)]
    rr = solve(ComplexLinearProblem.from_sequences(Ar, br), NumericMode.HIGH_PRECISION)
    assert rr.status == SolveStatus.SOLVED
    assert close(rr.solution[0], C(1.8), Decimal("1E-45"))
    assert close(rr.solution[1], C(1.4), Decimal("1E-45"))
    J = C(0, 1)
    Ai = [[2 * J, J], [J, 3 * J]]
    bi = [C(1, 1), C(2, -1)]
    ri = solve(ComplexLinearProblem.from_sequences(Ai, bi), NumericMode.HIGH_PRECISION)
    assert ri.status == SolveStatus.SOLVED
    assert ri.residual_norm is not None and ri.residual_norm <= Decimal("1E-40")


def test_hp_structural_singular_and_inconsistent():
    A = [[C(1), C(2)], [C(2), C(4)]]
    rs = solve(ComplexLinearProblem.from_sequences(A, [C(3), C(6)]),
               NumericMode.HIGH_PRECISION)
    assert rs.status == SolveStatus.SINGULAR
    assert (rs.rank_A, rs.rank_augmented) == (1, 1)
    ri = solve(ComplexLinearProblem.from_sequences(A, [C(3), C(7)]),
               NumericMode.HIGH_PRECISION)
    assert ri.status == SolveStatus.INCONSISTENT
    assert (ri.rank_A, ri.rank_augmented) == (1, 2)


# -- E. uncertainty policy ----------------------------------------------------------------------

def _tiny_shift(base: str, tiny: str):
    # Explicit-context addition: plain `Decimal(1) + Decimal("1E-45")`
    # would round the INPUT to the 28-digit ambient context and the test
    # would measure literal rounding instead of solver behavior.
    from academic_core.domain.engineering.math.trig import make_context

    return make_context().add(Decimal(base), Decimal(tiny))


def test_hp_near_dependent_is_uncertain_not_singular():
    # Rows agree to 45 digits: pivot ratio ~1E-45 < floor 1E-40.
    A = [[C(1), C(1)], [C(1), DecimalComplex(_tiny_shift("1", "1E-45"), Decimal(0))]]
    b = [C(2), C(2)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.NUMERICALLY_UNCERTAIN
    assert r.solution is not None  # evidence verdict, not a missing value
    assert any("pivot ratio" in d for d in r.diagnostics)


def test_hp_noise_level_rhs_is_uncertain_not_inconsistent():
    A = [[C(1), C(2)], [C(2), C(4)]]
    b = [C(3), DecimalComplex(_tiny_shift("6", "1E-45"), Decimal(0))]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.NUMERICALLY_UNCERTAIN
    assert any("noise" in d or "cannot certify" in d for d in r.diagnostics)


def test_hp_uncertain_reports_estimates_honestly():
    A = [[C(1), C(1)], [C(1), DecimalComplex(_tiny_shift("1", "1E-45"), Decimal(0))]]
    b = [C(2), C(2)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.NUMERICALLY_UNCERTAIN
    assert r.rank_A is not None and r.rank_augmented is not None
    assert r.backward_error is not None
    assert r.growth_factor is not None


def test_hp_growth_factor_reported_and_finite():
    A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    b = [C(1), C(2, 1)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert r.growth_factor is not None and r.growth_factor.is_finite()
    assert r.growth_factor >= 1


# -- F. residual / backward error ----------------------------------------------------------------------

def test_exact_residual_is_zero_triplet():
    A = [[R(1, 1), R(2)], [R(0, 1), R(3, -1)]]
    b = [R(1), R(2, 2)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.residual == (R(0), R(0))
    assert r.residual_norm == Decimal(0)
    assert r.backward_error == Decimal(0)


def test_hp_residual_definition_matvec():
    A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    b = [C(1), C(2, 1)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert r.residual is not None
    for got, want_b, ai in zip(matvec(A, r.solution), b, A):
        assert close(got, want_b, Decimal("1E-40")), ai
    assert r.residual_norm is not None and r.residual_norm <= Decimal("1E-40")


def test_hp_no_solution_has_no_residual():
    r = solve(ComplexLinearProblem.from_sequences(
        [[C(1), C(2)], [C(2), C(4)]], [C(3), C(6)]), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SINGULAR
    assert r.solution is None and r.residual is None
    assert r.residual_norm is None and r.backward_error is None


def test_backward_error_scale_invariance():
    from academic_core.domain.engineering.math.trig import make_context

    ctx = make_context()
    A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    b = [C(1), C(2, 1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    k = C("1E10")
    A2 = [[a * k for a in row] for row in A]
    b2 = [x * k for x in b]
    r2 = solve(ComplexLinearProblem.from_sequences(A2, b2), NumericMode.HIGH_PRECISION)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert close_list(list(r1.solution), list(r2.solution), Decimal("1E-38"))
    assert abs(ctx.subtract(r1.backward_error, r2.backward_error)) <= Decimal("1E-40")


def test_backward_error_zero_system_exact():
    # A=0, b=0, x=0: 0/0 scale with zero residual -> backward error 0.
    r = solve(ComplexLinearProblem.from_sequences(
        [[R(0)]], [R(0)]), NumericMode.EXACT)
    assert r.status == SolveStatus.SINGULAR
    assert r.backward_error is None  # no solution exists: None, explained


# -- G. scaling ----------------------------------------------------------------------

def test_scaling_extreme_diagonal_hp():
    n = 3
    A = [[C("1E-300") if i == j == 0 else (C("1E300") if i == j else C(0))
          for j in range(n)] for i in range(n)]
    b = [C("1E-300"), C("1E300"), C(1, 1)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert r.scaling_applied is True
    assert close(r.solution[0], C(1), Decimal("1E-40"))
    assert close(r.solution[1], C(1), Decimal("1E-40"))
    assert close(r.solution[2], C(1, 1) / C("1E300"), Decimal("1E-340"))


def test_scaling_row_units_do_not_change_solution():
    A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    b = [C(1), C(2, 1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    A2 = [[a * C(1000) for a in A[0]], list(A[1])]
    b2 = [b[0] * C(1000), b[1]]
    r2 = solve(ComplexLinearProblem.from_sequences(A2, b2), NumericMode.HIGH_PRECISION)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert close_list(list(r1.solution), list(r2.solution), Decimal("1E-38"))


def test_scaling_unknown_change_equivalence():
    # Column j *= d_j  <=>  unknown j in new units; x2[j] = x[j]/d_j.
    A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    b = [C(1), C(2, 1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    d = [C(2), C(3, 1)]
    A2 = [[A[i][j] * d[j] for j in range(2)] for i in range(2)]
    r2 = solve(ComplexLinearProblem.from_sequences(A2, list(b)),
               NumericMode.HIGH_PRECISION)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert close_list(list(r2.solution),
                       [r1.solution[j] / d[j] for j in range(2)], Decimal("1E-38"))


def test_scaling_preserves_ranks():
    from academic_core.domain.engineering.math.linsolve.scaling import equilibrate

    A = ((C(3), C(1, 1)), (C(1, -1), C(2)))
    b = (C(1), C(2, 1))
    a2, b2, rs, cs = equilibrate(A, b)
    assert len(rs) == 2 and len(cs) == 2
    assert all(s > 0 and s.is_finite() for s in list(rs) + list(cs))
    r_orig = solve(ComplexLinearProblem.from_sequences(
        [list(r) for r in A], list(b)), NumericMode.HIGH_PRECISION)
    r_scaled = solve(ComplexLinearProblem.from_sequences(
        [list(r) for r in a2], list(b2)), NumericMode.HIGH_PRECISION)
    assert (r_orig.rank_A, r_orig.rank_augmented) == (r_scaled.rank_A, r_scaled.rank_augmented)


def test_scaling_zero_row_left_for_structure():
    from academic_core.domain.engineering.math.linsolve.scaling import equilibrate

    A = ((C(1), C(2)), (C(0), C(0)))
    b = (C(3), C(0))
    a2, b2, rs, cs = equilibrate(A, b)
    assert rs[1] == Decimal(1)  # zero row: scale 1, structural fact preserved
    r = solve(ComplexLinearProblem.from_sequences(
        [list(r_) for r_ in A], list(b)), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SINGULAR


# -- H. metamorphic ----------------------------------------------------------------------

def test_metamorphic_system_scaling_exact():
    A = [[R(1, 1), R(2)], [R(0, 1), R(3, -1)]]
    b = [R(1), R(2, 2)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    k = R(5, -2)
    A2 = [[a * k for a in row] for row in A]
    b2 = [x * k for x in b]
    r2 = solve(ComplexLinearProblem.from_sequences(A2, b2), NumericMode.EXACT)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert r1.solution == r2.solution


def test_metamorphic_conjugation_both_modes():
    # det = (1+j)(3+j) - 2*(2j) = 2 (nonsingular by hand).
    A = [[R(1, 1), R(2)], [R(0, 2), R(3, 1)]]
    b = [R(1, 2), R(2)]
    p = ComplexLinearProblem.from_sequences(A, b)
    r = solve(p, NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    rc = solve(conjugate_system(p), NumericMode.EXACT)
    assert r.status == rc.status == SolveStatus.SOLVED
    assert rc.solution == tuple(e.conjugate() for e in r.solution)
    Ah = [[C(1, 1), C(2)], [C(0, 2), C(3, 1)]]
    bh = [C(1, 2), C(2)]
    ph = ComplexLinearProblem.from_sequences(Ah, bh)
    rh = solve(ph, NumericMode.HIGH_PRECISION)
    rhc = solve(conjugate_system(ph), NumericMode.HIGH_PRECISION)
    assert rh.status == rhc.status == SolveStatus.SOLVED
    assert close_list(list(rhc.solution),
                       [e.conjugate() for e in rh.solution], Decimal("1E-38"))


def test_metamorphic_row_permutation_both_modes():
    A = [[R(3), R(1, 1)], [R(1, -1), R(2)]]
    b = [R(1), R(2, 1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    r2 = solve(ComplexLinearProblem.from_sequences([A[1], A[0]], [b[1], b[0]]),
               NumericMode.EXACT)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert r1.solution == r2.solution  # RREF uniqueness: bit-identical
    Ah = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    bh = [C(1), C(2, 1)]
    h1 = solve(ComplexLinearProblem.from_sequences(Ah, bh), NumericMode.HIGH_PRECISION)
    h2 = solve(ComplexLinearProblem.from_sequences([Ah[1], Ah[0]], [bh[1], bh[0]]),
               NumericMode.HIGH_PRECISION)
    assert h1.status == h2.status == SolveStatus.SOLVED
    assert close_list(list(h1.solution), list(h2.solution), Decimal("1E-38"))


def test_metamorphic_column_permutation_exact():
    A = [[R(3), R(1, 1)], [R(1, -1), R(2)]]
    b = [R(1), R(2, 1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    A2 = [[row[1], row[0]] for row in A]
    r2 = solve(ComplexLinearProblem.from_sequences(A2, list(b)), NumericMode.EXACT)
    assert r1.status == r2.status == SolveStatus.SOLVED
    assert r2.solution == (r1.solution[1], r1.solution[0])


def test_metamorphic_linearity_exact():
    A = [[R(2), R(1, 1)], [R(1, -1), R(3)]]
    b1 = [R(1), R(0, 1)]
    b2 = [R(2, -1), R(1)]
    r1 = solve(ComplexLinearProblem.from_sequences(A, b1), NumericMode.EXACT)
    r2 = solve(ComplexLinearProblem.from_sequences(A, b2), NumericMode.EXACT)
    b12 = [x + y for x, y in zip(b1, b2)]
    r12 = solve(ComplexLinearProblem.from_sequences(A, b12), NumericMode.EXACT)
    assert r12.solution == tuple(x + y for x, y in zip(r1.solution, r2.solution))


# -- I. adversarial ----------------------------------------------------------------------

def test_adversarial_empty():
    with pytest.raises(EmptySystemError):
        ComplexLinearProblem.from_sequences([], [])
    with pytest.raises(EmptySystemError):
        ComplexLinearProblem.from_sequences([[R(1)]], [])


def test_adversarial_non_square():
    with pytest.raises(NonSquareError):
        ComplexLinearProblem.from_sequences([[R(1), R(2), R(3)], [R(4), R(5), R(6)]], [R(1), R(2)])
    with pytest.raises(NonSquareError):
        ComplexLinearProblem.from_sequences([[R(1), R(2)], [R(3)]], [R(1), R(2)])


def test_adversarial_dimension_mismatch():
    with pytest.raises(DimensionMismatchError):
        ComplexLinearProblem.from_sequences([[R(1), R(0)], [R(0), R(1)]], [R(1)])
    with pytest.raises(DimensionMismatchError):
        ComplexLinearProblem.from_sequences([[R(1), R(0)], [R(0), R(1)]], [R(1), R(2), R(3)])


def test_adversarial_bad_entry_types():
    good_row = [R(1), R(0)]
    for bad in (1.5, complex(1, 0), "1", True, None, [1]):
        with pytest.raises((InvalidEntryError, ComplexLinearError)):
            ComplexLinearProblem.from_sequences([good_row, [bad, R(0)]], [R(1), R(2)])


def test_adversarial_1x1_zero_cases():
    rs = solve(ComplexLinearProblem.from_sequences([[R(0)]], [R(0)]))
    assert rs.status == SolveStatus.SINGULAR
    ri = solve(ComplexLinearProblem.from_sequences([[R(0)]], [R(5)]))
    assert ri.status == SolveStatus.INCONSISTENT
    hs = solve(ComplexLinearProblem.from_sequences([[C(0)]], [C(0)]),
               NumericMode.HIGH_PRECISION)
    assert hs.status == SolveStatus.SINGULAR
    hi = solve(ComplexLinearProblem.from_sequences([[C(0)]], [C(5)]),
               NumericMode.HIGH_PRECISION)
    assert hi.status == SolveStatus.INCONSISTENT


def test_adversarial_huge_and_tiny_hp():
    A = [[C("1E300"), C(0)], [C(0), C("1E-300")]]
    b = [C("1E300"), C("1E-300")]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert close(r.solution[0], C(1), Decimal("1E-40"))
    assert close(r.solution[1], C(1), Decimal("1E-40"))


def test_adversarial_huge_exact():
    A = [[R(10**100), R(0)], [R(0), R(10**100)]]
    b = [R(10**100), R(2 * 10**100)]
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert r.status == SolveStatus.SOLVED
    assert r.solution == (R(1), R(2))


def test_adversarial_mixed_scales_dense():
    A = [[C("1E100"), C(1)], [C(1), C(2)]]
    x_true = [C(1, 1), C(2, -1)]
    b = list(matvec(A, x_true))  # forward product fixes the reference
    r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert close_list(list(r.solution), x_true, Decimal("1E-30"))


def test_adversarial_never_nan_inf_none():
    cases = [
        ([[C("1E300"), C(0)], [C(0), C("1E-300")]], [C("1E300"), C("1E-300")]),
        ([[C(1), C(1)], [C(1), C(1)]], [C(2), C(2)]),
        ([[C(1), C(2)], [C(2), C(4)]], [C(3), C(7)]),
        ([[C(0), C(0)], [C(0), C(0)]], [C(0), C(0)]),
    ]
    for A, b in cases:
        r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
        assert r.status in (SolveStatus.SOLVED, SolveStatus.SINGULAR,
                            SolveStatus.INCONSISTENT, SolveStatus.NUMERICALLY_UNCERTAIN)
        if r.solution is not None:
            for e in r.solution:
                assert e.re.is_finite() and e.im.is_finite()
                assert "NaN" not in (format(e.re, "f") + format(e.im, "f")).upper()
        if r.backward_error is not None:
            assert r.backward_error.is_finite()


def test_adversarial_mixed_rational_decimal_promotes():
    A = [[R(1, 1), C(2)], [C(1), R(2)]]
    b = [R(1), C(1)]
    p = ComplexLinearProblem.from_sequences(A, b)
    assert p.kind == "decimal" and p.input_promoted is True
    r = solve(p, NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED
    assert r.provenance["input_promoted"] is True
    with pytest.raises(InvalidModeError):
        solve(p, NumericMode.EXACT)


def test_adversarial_fraction_in_decimal_problem_promotes():
    p = ComplexLinearProblem.from_sequences(
        [[C(1), C(0)], [C(0), C(1)]],
        [Fraction(1, 3), Decimal("0.5")])
    assert p.input_promoted is True
    r = solve(p, NumericMode.HIGH_PRECISION)
    assert r.status == SolveStatus.SOLVED


# -- J. determinism / immutability ---------------------------------------------------------------

def test_determinism_100_repetitions_both_modes():
    A = [[R(3), R(1, 1), R(0, 2)], [R(1, -1), R(4), R(1)],
         [R(2), R(0, 1), R(5, -1)]]
    b = [R(1, 1), R(2), R(3, -1)]
    p = ComplexLinearProblem.from_sequences(A, b)
    first = solve(p, NumericMode.EXACT)
    first_dict = json.dumps(first.to_dict(), sort_keys=True)
    Ah = [[C(3), C(1, 1), C(0, 2)], [C(1, -1), C(4), C(1)],
          [C(2), C(0, 1), C(5, -1)]]
    bh = [C(1, 1), C(2), C(3, -1)]
    ph = ComplexLinearProblem.from_sequences(Ah, bh)
    hfirst = solve(ph, NumericMode.HIGH_PRECISION)
    hfirst_dict = json.dumps(hfirst.to_dict(), sort_keys=True)
    for _ in range(100):
        rep = solve(p, NumericMode.EXACT)
        assert rep.status == first.status and rep.solution == first.solution
        assert rep.rank_A == first.rank_A and rep.rank_augmented == first.rank_augmented
        assert rep.digest == first.digest
        assert json.dumps(rep.to_dict(), sort_keys=True) == first_dict
        hrep = solve(ph, NumericMode.HIGH_PRECISION)
        assert hrep.status == hfirst.status and hrep.solution == hfirst.solution
        assert hrep.digest == hfirst.digest
        assert json.dumps(hrep.to_dict(), sort_keys=True) == hfirst_dict


def test_immutability_inputs_untouched():
    A = [[R(3), R(1, 1)], [R(1, -1), R(2)]]
    b = [R(1), R(2, 1)]
    A_copy = [[e for e in row] for row in A]
    b_copy = list(b)
    solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    assert A == A_copy and b == b_copy
    Ah = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
    bh = [C(1), C(2, 1)]
    Ah_copy = [[e for e in row] for row in Ah]
    bh_copy = list(bh)
    solve(ComplexLinearProblem.from_sequences(Ah, bh), NumericMode.HIGH_PRECISION)
    assert Ah == Ah_copy and bh == bh_copy


def test_global_decimal_context_untouched_by_solver():
    from decimal import getcontext

    before = getcontext().prec
    getcontext().prec = 6
    try:
        A = [[C(3), C(1, 1)], [C(1, -1), C(2)]]
        b = [C(1), C(2, 1)]
        r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.HIGH_PRECISION)
        assert r.status == SolveStatus.SOLVED
        assert len(r.solution[0].re.as_tuple().digits) > 10
    finally:
        getcontext().prec = before
    assert getcontext().prec == before


# -- K. API / provenance ----------------------------------------------------------------------

def test_api_modes_and_dispatch():
    p_rational = ComplexLinearProblem.from_sequences([[R(2)]], [R(4)])
    assert solve(p_rational).numeric_mode == NumericMode.EXACT  # AUTO
    assert solve(p_rational, NumericMode.AUTO).numeric_mode == NumericMode.EXACT
    p_decimal = ComplexLinearProblem.from_sequences([[C(2)]], [C(4)])
    assert solve(p_decimal).numeric_mode == NumericMode.HIGH_PRECISION
    with pytest.raises(InvalidModeError):
        solve(p_decimal, NumericMode.EXACT)
    with pytest.raises(InvalidModeError):
        solve(p_rational, "exact")
    with pytest.raises(InvalidModeError):
        solve([[R(1)]], NumericMode.EXACT)


def test_result_fields_and_none_semantics():
    r = solve(ComplexLinearProblem.from_sequences([[R(2)]], [R(4)]))
    assert r.working_precision is None  # exact: no finite precision
    assert r.scaling_applied is False
    assert r.solution == (R(2),) and r.residual == (R(0),)
    assert isinstance(r.diagnostics, tuple) and len(r.diagnostics) >= 2
    h = solve(ComplexLinearProblem.from_sequences([[C(2)]], [C(4)]),
              NumericMode.HIGH_PRECISION)
    assert h.working_precision == 50 and h.scaling_applied is True


def test_provenance_keys_and_digest():
    r = solve(ComplexLinearProblem.from_sequences(
        [[R(2), R(0)], [R(0), R(2)]], [R(4), R(6)]))
    for key in ("engine", "version", "numeric_mode", "matrix_dimension",
                "rank_A", "rank_augmented", "status", "precision",
                "pivot_policy", "scaling_policy", "residual_definition",
                "backward_error_definition"):
        assert key in r.provenance, key
    assert r.provenance["engine"] == "f8d2-linsolve/1.0"
    assert "timestamp" not in json.dumps(r.to_dict())
    d1 = r.digest
    r2 = solve(ComplexLinearProblem.from_sequences(
        [[R(2), R(0)], [R(0), R(2)]], [R(4), R(6)]))
    assert r2.digest == d1
    r3 = solve(ComplexLinearProblem.from_sequences(
        [[R(2), R(0)], [R(0), R(2)]], [R(4), R(7)]))
    assert r3.digest != d1
    assert len(d1) == 64


# -- L. generality / performance ----------------------------------------------------------------------

def _tridiagonal_exact(n):
    A = [[R(0) for _ in range(n)] for _ in range(n)]
    for i in range(n):
        A[i][i] = R(4)
        if i > 0:
            A[i][i - 1] = R(1, 1)
        if i < n - 1:
            A[i][i + 1] = R(1, -1)
    return A, [R(1) for _ in range(n)]


def _dense_hp(n):
    A = [[C(4) if i == j else C("0.5", "0.25") for j in range(n)] for i in range(n)]
    return A, [C(1) for _ in range(n)]


def test_generality_sweep_both_modes():
    timings = {}
    for n in (1, 2, 3, 4, 8, 16, 32, 64):
        A, b = _tridiagonal_exact(n)
        t0 = time.time()
        r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
        timings[("exact", n)] = time.time() - t0
        assert r.status == SolveStatus.SOLVED
        assert tuple(matvec(A, r.solution)) == tuple(b)
        Ah, bh = _dense_hp(n)
        t0 = time.time()
        rh = solve(ComplexLinearProblem.from_sequences(Ah, bh), NumericMode.HIGH_PRECISION)
        timings[("hp", n)] = time.time() - t0
        assert rh.status == SolveStatus.SOLVED
        assert rh.backward_error is not None and rh.backward_error <= Decimal("1E-28")
    assert timings[("exact", 64)] < 90, timings
    assert timings[("hp", 64)] < 90, timings


def test_exact_8x8_matches_cramer_free_reference():
    # Reference: forward product of a chosen solution (independent path).
    import random

    rng = random.Random(99)
    n = 8
    A = [[R(rng.randint(-3, 3), rng.randint(-3, 3)) for _ in range(n)] for _ in range(n)]
    x_true = [R(rng.randint(-3, 3), rng.randint(-3, 3)) for _ in range(n)]
    b = list(matvec(A, x_true))
    det_r = solve(ComplexLinearProblem.from_sequences(A, b), NumericMode.EXACT)
    if det_r.status == SolveStatus.SOLVED:
        assert det_r.solution == tuple(x_true)


# -- M. security ------------------------------------------------------------------------------------

LINSOLVE_DIR = pathlib.Path(__file__).resolve().parents[1] / "src" / "academic_core" / "domain" / "engineering" / "math" / "linsolve"

FORBIDDEN_CALLS = {"eval", "exec", "compile", "__import__", "open", "input", "breakpoint"}
FORBIDDEN_IMPORT_ROOTS = {
    "os", "sys", "pathlib", "sqlite3", "urllib", "socket", "http",
    "ftplib", "subprocess", "pickle", "marshal", "ctypes",
    "PySide6", "numpy", "scipy", "math", "cmath",
}
FORBIDDEN_QUALIFIED = {
    "academic_core.domain.engineering.circuit",
    "academic_core.domain.engineering.units",
    "academic_core.domain.engineering.mna",
    "academic_core.infrastructure",
    "academic_core.application",
    "academic_core.app",
}


def _sources():
    return sorted(LINSOLVE_DIR.glob("*.py"))


def test_security_package_files_present():
    names = {p.name for p in _sources()}
    assert {"__init__.py", "errors.py", "problem.py", "result.py",
            "scaling.py", "exact.py", "high_precision.py", "solver.py"} <= names


def test_security_no_dangerous_calls():
    for path in _sources():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                assert node.func.id not in FORBIDDEN_CALLS, (path.name, node.func.id)


def test_security_no_forbidden_dependencies():
    # Real imports only (ast): docstring prose documents the boundary.
    for path in _sources():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for a in node.names:
                    assert a.name.split(".")[0] not in FORBIDDEN_IMPORT_ROOTS, (
                        path.name, a.name)
            elif isinstance(node, ast.ImportFrom) and node.module:
                assert node.module.split(".")[0] not in FORBIDDEN_IMPORT_ROOTS, (
                    path.name, node.module)
                for qual in FORBIDDEN_QUALIFIED:
                    assert node.module != qual and not node.module.startswith(qual + "."), (
                        path.name, node.module)


def test_security_no_float_complex_names_in_core():
    for name in ("exact.py", "high_precision.py", "scaling.py", "solver.py",
                 "problem.py", "result.py", "errors.py"):
        tree = ast.parse((LINSOLVE_DIR / name).read_text(encoding="utf-8"))
        names = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)}
        assert "float" not in names, name
        assert "complex" not in names, name


def test_security_solver_core_has_no_f8b_imports():
    import inspect

    import academic_core.domain.engineering.math.linsolve.exact as ex
    import academic_core.domain.engineering.math.linsolve.high_precision as hp
    import academic_core.domain.engineering.math.linsolve.solver as sv

    for mod in (ex, hp, sv):
        src = inspect.getsource(mod)
        assert "mna" not in src, mod.__name__
        assert "Fraction(" not in src, mod.__name__
