-- 004: study marks + sessions + notifications (renderer-agnostic locators).
CREATE TABLE IF NOT EXISTS tags (
  stable_id TEXT PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bookmarks (
  id INTEGER PRIMARY KEY AUTOINCREMENT, target_id TEXT NOT NULL,
  title TEXT NOT NULL, locator TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS annotations (
  id INTEGER PRIMARY KEY AUTOINCREMENT, target_id TEXT NOT NULL,
  body TEXT NOT NULL, color TEXT NOT NULL DEFAULT 'yellow',
  locator TEXT NOT NULL DEFAULT '', created TEXT);
CREATE TABLE IF NOT EXISTS study_spaces (
  id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id TEXT NOT NULL,
  exam_task_id TEXT NOT NULL, title TEXT NOT NULL, refs TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS study_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id TEXT NOT NULL,
  day TEXT NOT NULL, minutes INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '', due TEXT, read INTEGER NOT NULL DEFAULT 0);
