"""F8-P1 SISO LTI control layer (NEW): public surface."""

from academic_core.domain.engineering.control.errors import ControlError, ControlStatus
from academic_core.domain.engineering.control.locus import (
    angle_condition,
    asymptote_report,
    breakaway_points,
    jw_crossings,
    locus as trace_locus,
    locus_point,
    magnitude_gain,
)
from academic_core.domain.engineering.control.margins import (
    gain_crossovers,
    margins as compute_margins,
    phase_crossover_bisection,
    phase_crossovers,
)
from academic_core.domain.engineering.control.pid import (
    PIDController,
    UltimatePoint,
    ZieglerNicholsResult,
    closed_loop,
    pid_ideal,
    pid_parallel,
    pid_series,
    ultimate_gain,
    ziegler_nichols,
)
from academic_core.domain.engineering.control.poly import (
    MAX_POLY_DEGREE,
    Polynomial,
    durand_kerner_roots,
    make_polynomial,
    validate_roots,
)
from academic_core.domain.engineering.control.report import (
    SCHEMA,
    ControlDocument,
    compare,
    dumps,
    loads,
    replay,
)
from academic_core.domain.engineering.control.response import (
    decimal_exp,
    first_order_impulse,
    first_order_step,
    impulse_response,
    second_order_metrics,
    step_response,
)
from academic_core.domain.engineering.control.stability import (
    pole_inventory,
    routh_of_poly,
    routh_of_tf,
)
from academic_core.domain.engineering.control.statespace import (
    StateSpace,
    ctrb_rank,
    make_statespace,
    obsv_rank,
    ss_eigenvalues,
    ss_to_tf,
    tf_to_ss,
)
from academic_core.domain.engineering.control.tf import (
    RHO_CANCEL,
    ZPK,
    TransferFunctionTF,
    cancellation_report,
    complementary,
    feedback,
    feedback_positive,
    make_tf,
    parallel,
    sensitivity,
    series,
    tf_to_zpk,
    zpk_to_tf,
)

ENGINE_VERSION = "f8p1-control/1"

__all__ = [
    "ENGINE_VERSION",
    "ControlError",
    "ControlStatus",
    "MAX_POLY_DEGREE",
    "Polynomial",
    "durand_kerner_roots",
    "make_polynomial",
    "validate_roots",
    "TransferFunctionTF",
    "make_tf",
    "series",
    "parallel",
    "feedback",
    "feedback_positive",
    "sensitivity",
    "complementary",
    "ZPK",
    "tf_to_zpk",
    "zpk_to_tf",
    "cancellation_report",
    "RHO_CANCEL",
    "routh_of_poly",
    "routh_of_tf",
    "pole_inventory",
    "angle_condition",
    "magnitude_gain",
    "asymptote_report",
    "breakaway_points",
    "trace_locus",
    "locus_point",
    "jw_crossings",
    "gain_crossovers",
    "phase_crossovers",
    "phase_crossover_bisection",
    "compute_margins",
    "pid_parallel",
    "pid_ideal",
    "pid_series",
    "PIDController",
    "UltimatePoint",
    "ZieglerNicholsResult",
    "ziegler_nichols",
    "ultimate_gain",
    "closed_loop",
    "StateSpace",
    "make_statespace",
    "tf_to_ss",
    "ss_to_tf",
    "ctrb_rank",
    "obsv_rank",
    "ss_eigenvalues",
    "decimal_exp",
    "step_response",
    "impulse_response",
    "first_order_step",
    "first_order_impulse",
    "second_order_metrics",
    "SCHEMA",
    "ControlDocument",
    "dumps",
    "loads",
    "compare",
    "replay",
]
