"""F8-D3 General AC MNA engine: steady-state sinusoidal analysis.

Single positive operating frequency, ideal R/L/C plus independent V/I
sources, ``e^(+jwt)`` time convention, PEAK phasor amplitudes. Assembles
the complex MNA system from the canonical F6 ``Circuit`` (no second
circuit representation) and solves it exclusively through the F8-D2
complex linear solver (no second linear solver).

Entry points: :func:`solve_ac` (convenience, in-band statuses) and
:func:`build_ac_problem` (audit API, typed errors).
"""

from academic_core.domain.engineering.ac.errors import (
    ACFrequencyError,
    ACModeError,
    ACPhaseError,
    DimensionalityError,
    FloatingCircuitError,
    InvalidCircuitError,
    MissingReferenceError,
    UnsupportedElementError,
)
from academic_core.domain.engineering.ac.operating_point import (
    ACOperatingPoint,
    AMPLITUDE_CONVENTION,
    PHASE_CONVENTION,
    TIME_CONVENTION,
)
from academic_core.domain.engineering.ac.phasors import (
    magnitude,
    phase,
    rms_from_peak,
    to_polar,
)
from academic_core.domain.engineering.ac.impedance import (
    BASIS_CONSTITUTIVE,
    BASIS_OPERATING_RATIO,
    BASIS_PORT_DIRECT,
    BASIS_PORT_TEST,
    METHOD_AUTO,
    METHOD_DIRECT,
    METHOD_TEST,
    ImpedanceCategory,
    ImpedanceError,
    ImpedanceValue,
    PortDefinition,
    branch_admittance,
    branch_impedance,
    deactivate_sources,
    measure_port,
    operating_admittance,
    operating_impedance,
)
from academic_core.domain.engineering.ac.power import (
    ACPowerAnalysis,
    ConservationReport,
    ENGINE_VERSION as POWER_ENGINE_VERSION,
    ElementPower,
    POWER_CONVENTION,
    PowerAnalysisError,
    analyze_power,
    compute_element_power,
    verify_conservation,
)
from academic_core.domain.engineering.ac.problem import (
    ACBranch,
    ACMNAProblem,
    SUPPORTED_TYPES,
    build_ac_problem,
)
from academic_core.domain.engineering.ac.solution import (
    ACSolution,
    ACStatus,
    BranchCurrent,
    BranchVoltage,
    NodePhasor,
)
from academic_core.domain.engineering.ac.response import (
    BASIS_NETWORK_TRANSFER,
    BASIS_OPERATING_POINT_RATIO,
    Endpoint,
    TransferFunction,
    TransferKind,
    analyze_transfer,
    current_through,
    network_transfer,
    voltage_between,
)
from academic_core.domain.engineering.ac.response import (
    ResponseDefinition,
    SWEEP_COMPLETED,
    SWEEP_COMPLETED_WITH_POINT_FAILURES,
    SweepPoint,
    SweepResult,
    frequency_response,
    linear_frequencies,
)
from academic_core.domain.engineering.ac.bode import (
    BodeError,
    BodePoint,
    BodeResult,
    CutoffBracket,
    DecibelCategory,
    Extremum,
    MagnitudeResult,
    PassBand,
    analyze_bode,
    canonical_frequency_key,
    crossing_brackets,
    half_power_threshold_db,
    log_frequencies,
    magnitude_db,
    observed_extrema,
    reactance_zero_brackets,
    threshold_bands,
    unwrap_phases,
)
from academic_core.domain.engineering.ac.solver import (
    ENGINE_VERSION,
    solve_ac,
    solve_ac_problem,
)
from academic_core.domain.engineering.ac.thevenin import (
    ENGINE_VERSION as THEVENIN_ENGINE_VERSION,
    ACOnePortEquivalent,
    LoadCheck,
    analyze_ac_thevenin,
    analyze_ac_thevenin_problem,
    verify_with_load,
)
from academic_core.domain.engineering.ac.topology import (
    check_connected,
    cycle_basis,
    reference_net,
)

__all__ = [
    "ENGINE_VERSION",
    "ACFrequencyError",
    "ACModeError",
    "ACPhaseError",
    "DimensionalityError",
    "FloatingCircuitError",
    "InvalidCircuitError",
    "MissingReferenceError",
    "UnsupportedElementError",
    "ACOperatingPoint",
    "AMPLITUDE_CONVENTION",
    "PHASE_CONVENTION",
    "TIME_CONVENTION",
    "magnitude",
    "phase",
    "rms_from_peak",
    "to_polar",
    "BASIS_CONSTITUTIVE",
    "BASIS_OPERATING_RATIO",
    "BASIS_PORT_DIRECT",
    "BASIS_PORT_TEST",
    "METHOD_AUTO",
    "METHOD_DIRECT",
    "METHOD_TEST",
    "ImpedanceCategory",
    "ImpedanceError",
    "ImpedanceValue",
    "PortDefinition",
    "branch_admittance",
    "branch_impedance",
    "deactivate_sources",
    "measure_port",
    "operating_admittance",
    "operating_impedance",
    "ACPowerAnalysis",
    "ConservationReport",
    "POWER_ENGINE_VERSION",
    "ElementPower",
    "POWER_CONVENTION",
    "PowerAnalysisError",
    "analyze_power",
    "compute_element_power",
    "verify_conservation",
    "ACBranch",
    "ACMNAProblem",
    "SUPPORTED_TYPES",
    "build_ac_problem",
    "ACSolution",
    "ACStatus",
    "BranchCurrent",
    "BranchVoltage",
    "NodePhasor",
    "BASIS_NETWORK_TRANSFER",
    "BASIS_OPERATING_POINT_RATIO",
    "Endpoint",
    "TransferFunction",
    "TransferKind",
    "analyze_transfer",
    "current_through",
    "network_transfer",
    "voltage_between",
    "ResponseDefinition",
    "SweepPoint",
    "SweepResult",
    "SWEEP_COMPLETED",
    "SWEEP_COMPLETED_WITH_POINT_FAILURES",
    "frequency_response",
    "linear_frequencies",
    "BodeError",
    "BodePoint",
    "BodeResult",
    "CutoffBracket",
    "DecibelCategory",
    "Extremum",
    "MagnitudeResult",
    "PassBand",
    "analyze_bode",
    "canonical_frequency_key",
    "crossing_brackets",
    "half_power_threshold_db",
    "log_frequencies",
    "magnitude_db",
    "observed_extrema",
    "reactance_zero_brackets",
    "threshold_bands",
    "unwrap_phases",
    "solve_ac",
    "solve_ac_problem",
    "THEVENIN_ENGINE_VERSION",
    "ACOnePortEquivalent",
    "LoadCheck",
    "analyze_ac_thevenin",
    "analyze_ac_thevenin_problem",
    "verify_with_load",
    "check_connected",
    "cycle_basis",
    "reference_net",
]
